### ISSUE TITLE
Download TemStaPro

### ISSUE THREAD

**Issue by xing-he529** [ievapudz/TemStaPro#1]
Hi, 
Recently I've been working on protein thermostability prediction, and luckily, I found this cool program you generated. 
Now the environment was installed successfully, but I'm wondering how to download this program. 
Thanks!
X

**Comment by ievapudz** [comment]
Hello, 

I have just added an additional section in the program's README file. In a nutshell, the program can be downloaded by cloning the repository with `git clone https://github.com/ievapudz/TemStaPro.git` or by downloading the ZIP archyve of the program.

Hope that answers your question :)

**Comment by xing-he529** [comment]
> 

Thanks for your prompt reply. The software was successfully downloaded. I will have a try to use it😁

Thanks, X

**Comment by xing-he529** [comment]
Hello, 

This program can be successfully performed using my test dataset(~ 300 sequences), but it got an error when I used a larger dataset (~2w sequences), how can I solve this problem? 

The error I got:
```
2023-05-12 14:45:12.299011: beginning to load the model 
2023-05-12 14:45:43.333932: finished loading the model
Traceback (most recent call last):
  File "./temstapro", line 183, in <module>
    input_size=PARAMETERS["INPUT_SIZE"])
  File "/home/xinghe/app/TemStaPro/data_process.py", line 52, in collect_mean_embeddings
    sha256(sequences[seq_id].encode('utf-8')).hexdigest()))["mean_representations"]
KeyError: 'mean_representations'
```

btw, it's a nice program! Congratulations!

Thanks,X

**Comment by ievapudz** [comment]
I have created a dedicated issue for this case. Closing this one because the latest comment is not related to this issue.
